### ISSUE TITLE
Astro Template not loading

### ISSUE THREAD

**Issue by egriff38** [divriots/components.studio#4]
### 📖 Reproduction steps

1. Create a new astro template

### 🙁 Current Behavior

The following is rendered in the 'story' tab
WebAssembly: Response has unsupported MIME type 'text/plain; charset=utf-8' expected 'application/wasm'
??? (0:0)

### 🙂 Expected Behavior

The basic astro story should be rendered.

### 🔗 Link to the components

https://app.components.studio/edit/X9g1mypRVUpiTgAfJ6ZE/src/Greetings.astro?p=stories

### 🌐 What browser(s) are you seeing the problem on?

Firefox

### Browser version(s)

104.0.1 (64-bit)

**Comment by gqio** [comment]
Hello,

Sadly we dropped the support, it worked only pre v1.0 and a lot has changed since the release.
We didn't invest in the support of the new ^1.0.0 as of today.

Sorry for the inconvenience.

Best
